apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: cloud-learnings-staging

bases:
  - ../../base

namePrefix: staging-

patches:
  - path: replica-patch.yaml
  - path: resource-patch.yaml

commonLabels:
  environment: staging
