# TODO: Choose the right base image (hint: use python:3.12-slim)
FROM python:3.12-slim

# TODO: Set a working directory
WORKDIR /app

# TODO: Copy the server file

# TODO: Create a non-root user and switch to it

# TODO: Expose the port

# TODO: Add a HEALTHCHECK

# TODO: Set the command to run the server
