apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: cloud-learnings-dev

bases:
  - ../../base

namePrefix: dev-

patches:
  - path: replica-patch.yaml
  - path: env-patch.yaml

commonLabels:
  environment: dev
